jobs:
  sonar:
    if: github.repository == 'GoogleContainerTools/jib'
    name: Build with Sonar
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: date
      name: Get current date
      run: echo "date=$(date +'%Y-%m-%d' --utc)" >> $GITHUB_OUTPUT
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 11
    - continue-on-error: true
      name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-sonar-${{ steps.date.outputs.date }}
        path: ~/.sonar/cache
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')
          }}
        path: '~/.m2/repository

          ~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: Test w/ coverage
      run: './gradlew clean build jacocoTestReport --stacktrace

        '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      name: Build and analyze
      run: './gradlew sonarqube --stacktrace

        '
name: SonarCloud Analysis
on:
  repository_dispatch:
    types: trigger-ga___sonar.yml
